console.log(Math.PI);
let a = 5;
let b = 6.5;
let c = -50;
console.log(Math.sqrt(10));
console.log(Math.round(b));
console.log(Math.log(1));
console.log(Math.log(10));
console.log(Math.abs(c));
console.log(Math.ceil(c));
